<?php
/**
 * Laika Database Model
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP MVC Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Laika\Model\Tests;

use PHPUnit\Framework\TestCase;
use Laika\Model\Backup;
use Laika\Model\Connection;
use Laika\Model\Model;
use Laika\Model\Schema\Blueprint;
use Laika\Model\Schema\Schema;
use Laika\Model\Converter;
use Laika\Model\Converter\TypeLexicon;
use Laika\Model\Converter\Warning;
use Laika\Model\Drivers\AbstractDriver;
use Laika\Model\Drivers\DriverFactory;
use Laika\Model\Drivers\DriverInterface;
use Laika\Model\Exceptions\BackupException;
use Laika\Model\Exceptions\ConverterException;

class ConverterTest extends TestCase
{
    protected function setUp(): void
    {
        Connection::purge();
    }

    protected function tearDown(): void
    {
        // Purge first: SQLite keeps the file handle open, and Windows refuses
        // to unlink a file that still has one.
        Connection::purge();

        foreach ($this->tempFiles as $file) {
            if (is_file($file)) {
                @unlink($file);
            }
        }

        $this->tempFiles = [];
    }

    private function requireSqlite(): void
    {
        if (!in_array('pdo_sqlite', get_loaded_extensions(), true)) {
            $this->markTestSkipped('Extension pdo_sqlite is not loaded.');
        }
    }

    /**
     * Register the in-memory target every round-trip test applies to.
     *
     * Connection::get() memoises the handle, so ':memory:' survives across all
     * the calls in one test.
     */
    private function sqliteTarget(string $name = 'target'): string
    {
        $this->requireSqlite();
        Connection::add(['driver' => 'sqlite', 'database' => ':memory:'], $name);

        return $name;
    }

    // -----------------------------------------------------------------------
    // Construction
    // -----------------------------------------------------------------------

    public function testDriverAliasesAreCanonicalised(): void
    {
        $converter = new Converter('mariadb', 'postgres');

        $this->assertSame('mysql', $converter->sourceDialect());
        $this->assertSame('pgsql', $converter->targetDialect());
    }

    public function testUnknownSourceDriverThrows(): void
    {
        $this->expectException(ConverterException::class);
        new Converter('nosuchdb', 'pgsql');
    }

    /**
     * Every built-in driver now has a grammar, so the only way to reach this
     * branch is a custom driver registered without one.
     */
    public function testTargetWithoutAGrammarThrows(): void
    {
        DriverFactory::register('grammarless', GrammarlessDriver::class);

        try {
            $this->expectException(ConverterException::class);
            $this->expectExceptionMessage('No grammar for target driver');

            new Converter('mysql', 'grammarless');
        } finally {
            DriverFactory::unregister('grammarless');
        }
    }

    /** Oracle and Firebird used to land in the branch above; they no longer do. */
    #[\PHPUnit\Framework\Attributes\DataProvider('newTargetProvider')]
    public function testOracleAndFirebirdAreSupportedTargets(string $target, string $expected): void
    {
        $converter = new Converter('mysql', $target);

        $out = $converter->convert(
            'CREATE TABLE `users` ('
            . '`id` bigint unsigned NOT NULL AUTO_INCREMENT,'
            . '`username` varchar(50) NOT NULL,'
            . 'PRIMARY KEY (`id`));'
        );

        $this->assertStringContainsString($expected, $out);
    }

    /** @return array<string,array{string,string}> */
    public static function newTargetProvider(): array
    {
        return [
            'oci'      => ['oci',      '"id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY'],
            'oracle'   => ['oracle',   'VARCHAR2(50)'],
            'firebird' => ['firebird', '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY'],
            'ibase'    => ['ibase',    'VARCHAR(50)'],
        ];
    }

    // -----------------------------------------------------------------------
    // DDL
    // -----------------------------------------------------------------------

    public function testMySqlCreateTableToPostgres(): void
    {
        $sql = <<<'SQL'
        CREATE TABLE `users` (
          `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
          `email` varchar(190) NOT NULL,
          `nickname` varchar(60) DEFAULT NULL,
          `status` tinyint(4) NOT NULL DEFAULT 0,
          `balance` double DEFAULT NULL,
          `bio` longtext,
          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (`id`),
          UNIQUE KEY `uq_email` (`email`),
          KEY `idx_status` (`status`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        SQL;

        $converter = new Converter('mysql', 'pgsql');

        $this->assertSame(
            "CREATE TABLE \"users\" (\n"
            . "  \"id\" SERIAL NOT NULL,\n"
            . "  \"email\" VARCHAR(190) NOT NULL,\n"
            // An explicit "DEFAULT NULL" in the source is preserved rather than
            // dropped — it is valid in every target and faithful to the input.
            . "  \"nickname\" VARCHAR(60) NULL DEFAULT NULL,\n"
            . "  \"status\" SMALLINT NOT NULL DEFAULT 0,\n"
            . "  \"balance\" DOUBLE PRECISION NULL DEFAULT NULL,\n"
            . "  \"bio\" TEXT NULL,\n"
            . "  \"created_at\" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n"
            . "  PRIMARY KEY (\"id\"),\n"
            . "  CONSTRAINT \"uq_users_email\" UNIQUE (\"email\")\n"
            . ");\n"
            . 'CREATE INDEX "idx_users_status" ON "users" ("status");',
            $converter->convert($sql)
        );

        $this->assertFalse($converter->report()->hasWarnings(), 'Plain DDL should convert cleanly');
    }

    public function testAutoIncrementBecomesTheTargetsOwnConvention(): void
    {
        $sql = 'CREATE TABLE t (`id` bigint unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`id`));';

        $this->assertStringContainsString('BIGSERIAL', (new Converter('mysql', 'pgsql'))->convert($sql));
        $this->assertStringContainsString('IDENTITY(1,1)', (new Converter('mysql', 'sqlsrv'))->convert($sql));
        $this->assertStringContainsString(
            'INTEGER PRIMARY KEY AUTOINCREMENT',
            (new Converter('mysql', 'sqlite'))->convert($sql)
        );
    }

    public function testUnsignedIsDroppedForTargetsThatRejectIt(): void
    {
        $sql = 'CREATE TABLE t (`hits` int unsigned NOT NULL);';

        $this->assertStringNotContainsString('UNSIGNED', (new Converter('mysql', 'pgsql'))->convert($sql));
        $this->assertStringContainsString('UNSIGNED', (new Converter('mysql', 'mysql'))->convert($sql));
    }

    public function testEnumIsEmulatedOnTargetsWithoutIt(): void
    {
        $sql = "CREATE TABLE t (`role` enum('admin','user') NOT NULL);";

        $this->assertStringContainsString(
            "CHECK (role IN ('admin', 'user'))",
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
        $this->assertStringContainsString(
            "ENUM('admin', 'user')",
            (new Converter('pgsql', 'mysql'))->convert("CREATE TABLE t (role varchar(20));")
                ? (new Converter('mysql', 'mysql'))->convert($sql)
                : ''
        );
    }

    public function testForeignKeyIsCarriedAcross(): void
    {
        $sql = <<<'SQL'
        CREATE TABLE `posts` (
          `id` int NOT NULL,
          `author_id` int NOT NULL,
          CONSTRAINT `fk_author` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        );
        SQL;

        $out = (new Converter('mysql', 'pgsql'))->convert($sql);

        $this->assertStringContainsString(
            'CONSTRAINT "fk_posts_author" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE RESTRICT',
            $out
        );
    }

    public function testCompositeForeignKeyIsReportedNotSilentlyDropped(): void
    {
        $sql = <<<'SQL'
        CREATE TABLE t (
          a int NOT NULL,
          b int NOT NULL,
          FOREIGN KEY (a, b) REFERENCES other (x, y)
        );
        SQL;

        $converter = new Converter('mysql', 'pgsql');
        $converter->convert($sql);

        $warnings = $converter->report()->warningsOfLevel(Warning::LEVEL_LOSSY);

        $this->assertNotEmpty($warnings);
        $this->assertStringContainsString('composite foreign key', $warnings[0]->reason);
    }

    public function testCheckConstraintIsReported(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $converter->convert('CREATE TABLE t (a int, CHECK (a > 0));');

        $this->assertStringContainsString(
            'CHECK constraint dropped',
            (string) $converter->report()->warnings()[0]
        );
    }

    public function testUnknownTypeIsCarriedThroughWithAWarning(): void
    {
        $converter = new Converter('pgsql', 'mysql');
        $out       = $converter->convert('CREATE TABLE places (id int, geom GEOMETRY NOT NULL, net INET);');

        // Carried verbatim rather than guessed at or dropped.
        $this->assertStringContainsString('`geom` GEOMETRY NOT NULL', $out);
        $this->assertStringContainsString('`net` INET', $out);

        $reasons = array_map(fn(Warning $w) => $w->reason, $converter->report()->warnings());
        $this->assertStringContainsString('GEOMETRY', implode(' ', $reasons));
        $this->assertStringContainsString('INET', implode(' ', $reasons));
    }

    public function testPostgresSerialToMySqlAutoIncrement(): void
    {
        $sql = <<<'SQL'
        CREATE TABLE "users" (
            "id" SERIAL NOT NULL,
            "email" character varying(190) NOT NULL,
            "score" double precision,
            "meta" jsonb,
            PRIMARY KEY ("id")
        );
        SQL;

        $out = (new Converter('pgsql', 'mysql'))->convert($sql);

        $this->assertStringContainsString('`id` INT UNSIGNED NOT NULL AUTO_INCREMENT', $out);
        $this->assertStringContainsString('`email` VARCHAR(190) NOT NULL', $out);
        $this->assertStringContainsString('`score` DOUBLE', $out);
        $this->assertStringContainsString('`meta` JSON', $out);
    }

    public function testStandaloneCreateIndexIsTranslated(): void
    {
        $out = (new Converter('pgsql', 'mysql'))->convert('CREATE INDEX idx_email ON users (email);');

        $this->assertSame('CREATE INDEX `idx_email` ON `users` (`email`);', $out);
    }

    public function testDropTableListIsSplitPerTable(): void
    {
        $out = (new Converter('mysql', 'pgsql'))->convert('DROP TABLE IF EXISTS `a`, `b`;');

        $this->assertSame(
            "DROP TABLE IF EXISTS \"a\";\nDROP TABLE IF EXISTS \"b\";",
            $out
        );
    }

    // -----------------------------------------------------------------------
    // INSERT and literals
    // -----------------------------------------------------------------------

    public function testExtendedInsertIsSplitIntoRows(): void
    {
        $sql = "INSERT INTO `t` (`a`, `b`) VALUES (1,'x'),(2,'y'),(3,'z');";

        $this->assertSame(
            "INSERT INTO \"t\" (\"a\", \"b\") VALUES (1, 'x');\n"
            . "INSERT INTO \"t\" (\"a\", \"b\") VALUES (2, 'y');\n"
            . "INSERT INTO \"t\" (\"a\", \"b\") VALUES (3, 'z');",
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
    }

    public function testMySqlBackslashEscapesBecomeStandardDoubling(): void
    {
        $sql = "INSERT INTO t (a) VALUES ('it\\'s');";

        $this->assertSame(
            "INSERT INTO \"t\" (\"a\") VALUES ('it''s');",
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
    }

    public function testExistingDoubledQuotesSurvive(): void
    {
        $sql = "INSERT INTO t (a) VALUES ('quo''ted');";

        $this->assertSame(
            "INSERT INTO \"t\" (\"a\") VALUES ('quo''ted');",
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
    }

    /** @dataProvider hexTargetProvider */
    public function testHexBlobLiteralPerTarget(string $target, string $expected): void
    {
        $out = (new Converter('mysql', $target))->convert('INSERT INTO t (a) VALUES (0xDEADBEEF);');

        $this->assertStringContainsString($expected, $out);
    }

    /** @return array<string,array{string,string}> */
    public static function hexTargetProvider(): array
    {
        return [
            'pgsql'  => ['pgsql', "'\\xdeadbeef'::bytea"],
            'sqlite' => ['sqlite', "X'DEADBEEF'"],
            'mysql'  => ['mysql', '0xDEADBEEF'],
        ];
    }

    public function testBooleanColumnGetsATrueLiteralInPostgres(): void
    {
        $sql = "CREATE TABLE t (`flag` boolean NOT NULL);\n"
            . 'INSERT INTO t (`flag`) VALUES (1),(0);';

        $out = (new Converter('mysql', 'pgsql'))->convert($sql);

        $this->assertStringContainsString('VALUES (TRUE);', $out);
        $this->assertStringContainsString('VALUES (FALSE);', $out);
    }

    public function testBooleanStaysNumericForTargetsThatAcceptIt(): void
    {
        $sql = "CREATE TABLE t (`flag` boolean NOT NULL);\n"
            . 'INSERT INTO t (`flag`) VALUES (1);';

        $this->assertStringContainsString('VALUES (1);', (new Converter('mysql', 'sqlite'))->convert($sql));
    }

    public function testZeroDateBecomesNullWithAWarning(): void
    {
        $sql = "CREATE TABLE t (`d` date);\n"
            . "INSERT INTO t (`d`) VALUES ('0000-00-00');";

        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert($sql);

        $this->assertStringContainsString('VALUES (NULL);', $out);
        $this->assertStringContainsString('Zero date', (string) $converter->report()->warnings()[0]);
    }

    public function testNullAndKeywordsPassThrough(): void
    {
        $sql = "INSERT INTO t (a, b) VALUES (NULL, CURRENT_TIMESTAMP);";

        $this->assertSame(
            'INSERT INTO "t" ("a", "b") VALUES (NULL, CURRENT_TIMESTAMP);',
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
    }

    public function testSemicolonInsideAValueDoesNotSplitTheStatement(): void
    {
        $sql = "INSERT INTO t (a) VALUES ('a;b');";

        $this->assertSame(
            "INSERT INTO \"t\" (\"a\") VALUES ('a;b');",
            (new Converter('mysql', 'pgsql'))->convert($sql)
        );
    }

    // -----------------------------------------------------------------------
    // Default expressions
    // -----------------------------------------------------------------------

    /**
     * MariaDB writes `current_timestamp()` with parentheses, which SQLite
     * rejects outright. Found by converting a real mysqldump.
     *
     * @dataProvider nowFunctionProvider
     */
    public function testNowFunctionsNormaliseToTheStandardKeyword(string $default, string $expected): void
    {
        $sql = "CREATE TABLE t (`c` timestamp NOT NULL DEFAULT {$default});";

        $this->assertStringContainsString(
            "DEFAULT {$expected}",
            (new Converter('mysql', 'sqlite'))->convert($sql)
        );
    }

    /** @return array<string,array{string,string}> */
    public static function nowFunctionProvider(): array
    {
        return [
            'mariadb parens'   => ['current_timestamp()', 'CURRENT_TIMESTAMP'],
            'bare keyword'     => ['CURRENT_TIMESTAMP', 'CURRENT_TIMESTAMP'],
            'now()'            => ['now()', 'CURRENT_TIMESTAMP'],
            'with precision'   => ['current_timestamp(6)', 'CURRENT_TIMESTAMP'],
            'sqlsrv getdate()' => ['getdate()', 'CURRENT_TIMESTAMP'],
            'curdate()'        => ['curdate()', 'CURRENT_DATE'],
        ];
    }

    public function testNormalisedTimestampDefaultActuallyExecutes(): void
    {
        $target = $this->sqliteTarget();
        $sql    = 'CREATE TABLE t (`id` int NOT NULL, `created_at` timestamp NOT NULL DEFAULT current_timestamp());';

        (new Converter('mysql', 'sqlite'))->apply($sql, $target);

        $model = new Model($target);
        $model->table('t')->insert(['id' => 1]);

        $row = $model->table('t')->where(['id' => 1])->first();
        $this->assertNotEmpty($row['created_at']);
    }

    public function testPostgresSequenceDefaultIsDropped(): void
    {
        // The target declares its own auto-increment; carrying nextval() across
        // would reference a sequence that does not exist there.
        $sql = <<<'SQL'
        CREATE TABLE "t" (
            "id" integer DEFAULT nextval('t_id_seq'::regclass) NOT NULL
        );
        SQL;

        $out = (new Converter('pgsql', 'mysql'))->convert($sql);

        $this->assertStringNotContainsString('nextval', $out);
    }

    public function testUnknownFunctionDefaultIsCarriedThroughWithAWarning(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert('CREATE TABLE t (`c` char(36) DEFAULT uuid());');

        $this->assertStringContainsString('DEFAULT uuid()', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_LOSSY));
    }

    // -----------------------------------------------------------------------
    // Database-level statements
    // -----------------------------------------------------------------------

    /**
     * mysqldump --databases emits CREATE DATABASE and USE. Passing those
     * through breaks execution: SQLite has no such statements at all, and the
     * target database is already chosen by the connection.
     *
     * @dataProvider databaseStatementProvider
     */
    public function testDatabaseLevelStatementsAreDropped(string $sql): void
    {
        $converter = new Converter('mysql', 'sqlite');
        $out       = $converter->convert($sql . "\nCREATE TABLE t (a int);");

        $this->assertStringNotContainsString('DATABASE', strtoupper($out));
        $this->assertStringNotContainsString('USE ', strtoupper($out));
        $this->assertStringContainsString('CREATE TABLE "t"', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_SKIPPED));
    }

    /** @return array<string,array{string}> */
    public static function databaseStatementProvider(): array
    {
        return [
            'create database'  => ['CREATE DATABASE `app`;'],
            'create if exists' => ['CREATE DATABASE /*!32312 IF NOT EXISTS*/ `app`;'],
            'use'              => ['USE `app`;'],
            'drop database'    => ['DROP DATABASE `app`;'],
            'create schema'    => ['CREATE SCHEMA `app`;'],
        ];
    }

    // -----------------------------------------------------------------------
    // Warnings and strictness
    // -----------------------------------------------------------------------

    public function testSessionStatementsAreDropped(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert("SET NAMES utf8mb4;\nCREATE TABLE t (a int);");

        $this->assertStringNotContainsString('SET NAMES', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_SKIPPED));
    }

    /**
     * mysqldump brackets every table in LOCK/UNLOCK. Passing those through
     * verbatim put backticked MySQL in front of PostgreSQL and aborted apply()
     * on the first table.
     *
     * @dataProvider maintenanceStatementProvider
     */
    public function testMaintenanceStatementsAreDropped(string $sql): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert($sql . "
CREATE TABLE `t` (`a` int);");

        $this->assertStringNotContainsString('`', $out, 'MySQL quoting leaked into the output');
        $this->assertStringNotContainsString('LOCK', strtoupper($out));
        $this->assertStringNotContainsString('FLUSH', strtoupper($out));

        // The rest of the stream must survive the drop.
        $this->assertStringContainsString('CREATE TABLE "t"', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_SKIPPED));
        $this->assertEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_PASSTHROUGH));
    }

    /** @return array<string,array{string}> */
    public static function maintenanceStatementProvider(): array
    {
        return [
            'lock write'     => ['LOCK TABLES `t` WRITE;'],
            'lock read'      => ['LOCK TABLES `t` READ;'],
            'unlock'         => ['UNLOCK TABLES;'],
            'flush'          => ['FLUSH TABLES;'],
            'analyze'        => ['ANALYZE TABLE `t`;'],
            'optimize'       => ['OPTIMIZE TABLE `t`;'],
            'repair'         => ['REPAIR TABLE `t`;'],
            'checksum'       => ['CHECKSUM TABLE `t`;'],
        ];
    }

    /** The exact LOCK/INSERT/UNLOCK sandwich mysqldump writes per table. */
    public function testMysqldumpLockSandwichRoundTripsToSqlite(): void
    {
        $this->requireSqlite();

        $dump = <<<'SQL'
--
-- Dumping data for table `mod_invoicedata`
--

LOCK TABLES `mod_invoicedata` WRITE;
/*!40000 ALTER TABLE `mod_invoicedata` DISABLE KEYS */;
INSERT INTO `mod_invoicedata` (`id`, `label`) VALUES (1,'first'),(2,'second');
/*!40000 ALTER TABLE `mod_invoicedata` ENABLE KEYS */;
UNLOCK TABLES;
SQL;

        $target    = $this->sqliteTarget();
        $converter = new Converter('mysql', 'sqlite');
        $source    = "CREATE TABLE `mod_invoicedata` (`id` int NOT NULL, `label` varchar(50));
" . $dump;

        $out = $converter->convert($source);

        $this->assertStringNotContainsString('`', $out);
        $this->assertStringNotContainsString('LOCK TABLES', strtoupper($out));

        // apply() re-reads the source through StatementReader, so the sandwich
        // is split by the library rather than by a hand-rolled explode().
        $converter->apply($source, $target);

        $rows = (new Model($target))->table('mod_invoicedata')->order('id')->get();

        $this->assertSame(
            [['id' => 1, 'label' => 'first'], ['id' => 2, 'label' => 'second']],
            $rows
        );
    }

    // -----------------------------------------------------------------------
    // Zero dates in column DEFAULTs
    //
    // '0000-00-00' is a legal MySQL default that PostgreSQL rejects outright.
    // NULL is not a substitute because these columns are typically NOT NULL,
    // so the clause is dropped and the column keeps its type.
    // -----------------------------------------------------------------------

    /** @dataProvider zeroDateTargetProvider */
    public function testZeroDateDefaultIsDropped(string $to): void
    {
        $converter = new Converter('mysql', $to);
        $out       = $converter->convert(
            "CREATE TABLE `t` ("
            . "`date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00', "
            . "`d2` date NOT NULL DEFAULT '0000-00-00');"
        );

        $this->assertStringNotContainsString('0000-00-00', $out);

        // Dropped, not silently turned into a fabricated value. Blueprint's
        // timestamp() bakes in a CURRENT_TIMESTAMP that has to be cleared too.
        $this->assertStringNotContainsString('CURRENT_TIMESTAMP', $out);
        $this->assertStringNotContainsString('DEFAULT', strtoupper($out));

        // The columns survive, but NOT NULL goes with the default: a zero date
        // means "absent", and the values translate to NULL.
        $this->assertStringNotContainsString('NOT NULL', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_LOSSY));
    }

    /** @return array<string,array{string}> */
    public static function zeroDateTargetProvider(): array
    {
        return [
            'pgsql'  => ['pgsql'],
            'sqlite' => ['sqlite'],
            'sqlsrv' => ['sqlsrv'],
        ];
    }

    public function testZeroDateDefaultSurvivesMySqlToMySql(): void
    {
        $converter = new Converter('mysql', 'mysql');
        $out       = $converter->convert(
            "CREATE TABLE `t` (`date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00');"
        );

        $this->assertStringContainsString("'0000-00-00 00:00:00'", $out);
        $this->assertEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_LOSSY));
    }

    public function testGenuineDefaultsAreNotCollateralDamage(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert(
            "CREATE TABLE `t` ("
            . "`ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "
            . "`n` int NOT NULL DEFAULT 7, "
            . "`s` varchar(10) NOT NULL DEFAULT 'x');"
        );

        $this->assertStringContainsString('DEFAULT CURRENT_TIMESTAMP', $out);
        $this->assertStringContainsString('DEFAULT 7', $out);
        $this->assertStringContainsString("DEFAULT 'x'", $out);
    }

    public function testZeroDateTableActuallyExecutes(): void
    {
        $target    = $this->sqliteTarget();
        $converter = new Converter('mysql', 'sqlite');

        $converter->apply(
            "CREATE TABLE `t` (`id` int NOT NULL, `date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00');",
            $target
        );

        $model = new Model($target);
        $model->table('t')->insert(['id' => 1, 'date' => '2024-01-01 00:00:00']);

        $this->assertSame(
            '2024-01-01 00:00:00',
            $model->table('t')->where(['id' => 1])->first()['date']
        );

        // The zero-date row must land too — that is the whole point of relaxing
        // NOT NULL, and it is where apply() failed against PostgreSQL.
        $converter->apply("INSERT INTO `t` (`id`, `date`) VALUES (2, '0000-00-00 00:00:00');", $target);

        $this->assertNull($model->table('t')->where(['id' => 2])->first()['date']);
    }

    public function testOnlyZeroDateColumnsLoseNotNull(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert(
            "CREATE TABLE `t` ("
            . "`zero` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', "
            . "`plain` datetime NOT NULL, "
            . "`named` varchar(10) NOT NULL DEFAULT 'x');"
        );

        $this->assertStringContainsString('"zero" TIMESTAMP NULL', $out);
        $this->assertStringContainsString('"plain" TIMESTAMP NOT NULL', $out);
        $this->assertStringContainsString('"named" VARCHAR(10) NOT NULL', $out);
    }

    public function testUnsupportedStatementIsPassedThroughNotDropped(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $out       = $converter->convert('CREATE VIEW v AS SELECT 1;');

        $this->assertStringContainsString('CREATE VIEW v AS SELECT 1;', $out);
        $this->assertNotEmpty($converter->report()->warningsOfLevel(Warning::LEVEL_PASSTHROUGH));
    }

    public function testStrictModeThrowsOnTheFirstWarning(): void
    {
        $converter = new Converter('mysql', 'pgsql', strict: true);

        $this->expectException(ConverterException::class);
        $converter->convert('CREATE VIEW v AS SELECT 1;');
    }

    public function testReportCountsStatementsByKind(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $converter->convert(
            "CREATE TABLE t (a int);\n"
            . "INSERT INTO t (a) VALUES (1);\n"
            . "INSERT INTO t (a) VALUES (2);\n"
            . 'DROP TABLE t;'
        );

        $this->assertSame(
            ['create_table' => 1, 'insert' => 2, 'drop_table' => 1],
            $converter->report()->counts()
        );
        $this->assertSame(4, $converter->report()->statementCount());
    }

    public function testResetClearsState(): void
    {
        $converter = new Converter('mysql', 'pgsql');
        $converter->convert('CREATE VIEW v AS SELECT 1;');
        $this->assertTrue($converter->report()->hasWarnings());

        $converter->reset();

        $this->assertFalse($converter->report()->hasWarnings());
        $this->assertSame(0, $converter->report()->statementCount());
    }

    // -----------------------------------------------------------------------
    // Streaming and files
    // -----------------------------------------------------------------------

    public function testStreamYieldsOneStatementAtATime(): void
    {
        $converter = new Converter('mysql', 'pgsql');

        $statements = iterator_to_array(
            $converter->stream("CREATE TABLE t (a int);\nINSERT INTO t (a) VALUES (1),(2);"),
            false
        );

        $this->assertCount(3, $statements);
        $this->assertStringStartsWith('CREATE TABLE', $statements[0]);
        $this->assertStringStartsWith('INSERT INTO', $statements[1]);
    }

    public function testConvertFileWritesEveryStatement(): void
    {
        $source      = tempnam(sys_get_temp_dir(), 'laika-src-');
        $destination = tempnam(sys_get_temp_dir(), 'laika-dst-');

        file_put_contents($source, "CREATE TABLE t (a int);\nINSERT INTO t (a) VALUES (1),(2),(3);");

        try {
            $written = (new Converter('mysql', 'pgsql'))->convertFile($source, $destination);

            $this->assertSame(4, $written);

            $output = file_get_contents($destination);
            $this->assertStringContainsString('CREATE TABLE "t"', $output);
            $this->assertSame(3, substr_count($output, 'INSERT INTO "t"'));
        } finally {
            @unlink($source);
            @unlink($destination);
        }
    }

    // -----------------------------------------------------------------------
    // The real proof: converted SQL must execute and round-trip the data
    // -----------------------------------------------------------------------

    public function testMySqlDumpConvertedToSqliteExecutesAndKeepsItsData(): void
    {
        $this->requireSqlite();

        $dump = <<<'SQL'
        -- MySQL dump 10.13
        /*!40101 SET @saved_cs_client = @@character_set_client */;
        SET NAMES utf8mb4;

        DROP TABLE IF EXISTS `authors`;
        CREATE TABLE `authors` (
          `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(120) NOT NULL,
          `active` tinyint(1) NOT NULL DEFAULT 1,
          PRIMARY KEY (`id`),
          UNIQUE KEY `uq_name` (`name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

        INSERT INTO `authors` (`id`, `name`, `active`) VALUES
         (1,'Ada Lovelace',1),
         (2,'O\'Brien; the second',0),
         (3,'quo''ted',1);

        DROP TABLE IF EXISTS `posts`;
        CREATE TABLE `posts` (
          `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
          `author_id` int(10) unsigned NOT NULL,
          `title` varchar(190) NOT NULL,
          `body` longtext,
          `score` double DEFAULT NULL,
          PRIMARY KEY (`id`),
          KEY `idx_author` (`author_id`),
          CONSTRAINT `fk_author` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

        INSERT INTO `posts` (`id`, `author_id`, `title`, `body`, `score`) VALUES
         (1,1,'First; post','Body with a ; semicolon',9.5),
         (2,2,'Second','It\'s fine',NULL);
        SQL;

        $target    = $this->sqliteTarget();
        $converter = new Converter('mysql', 'sqlite');

        $converter->apply($dump, $target);

        // apply() disables FK checks for the duration and restores them in its
        // finally, so enforcement is turned on after the load, not before.
        Schema::on($target)->enableForeignKeyChecks();

        $model = new Model($target);

        $this->assertSame(
            [
                ['id' => 1, 'name' => 'Ada Lovelace', 'active' => 1],
                ['id' => 2, 'name' => "O'Brien; the second", 'active' => 0],
                ['id' => 3, 'name' => "quo'ted", 'active' => 1],
            ],
            $model->table('authors')->select(['id', 'name', 'active'])->order('id')->get()
        );

        $posts = $model->table('posts')
            ->select(['id', 'author_id', 'title', 'body', 'score'])
            ->order('id')
            ->get();

        $this->assertSame('First; post', $posts[0]['title']);
        $this->assertSame('Body with a ; semicolon', $posts[0]['body']);
        $this->assertSame(9.5, $posts[0]['score']);
        $this->assertSame("It's fine", $posts[1]['body']);
        $this->assertNull($posts[1]['score']);

        // The index survived as a separate CREATE INDEX statement. Schema has
        // hasTable()/hasColumn() but no index introspection, so this goes
        // through Model::execute() — the sanctioned prepared-and-logged route.
        $indexes = $model->execute(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'posts'"
        )->fetchAll(\PDO::FETCH_COLUMN);
        $this->assertContains('idx_posts_author', $indexes);

        // And the foreign key is live. Model::insert() wraps the driver error.
        $this->expectException(\RuntimeException::class);
        $model->table('posts')->insert(['id' => 99, 'author_id' => 404, 'title' => 'orphan']);
    }

    public function testApplyExecutesAgainstARegisteredConnection(): void
    {
        $target = $this->sqliteTarget();

        $dump = "CREATE TABLE `t` (`id` int NOT NULL AUTO_INCREMENT, `v` varchar(20), PRIMARY KEY (`id`));
"
            . "INSERT INTO `t` (`id`, `v`) VALUES (1,'a'),(2,'b');";

        $executed = (new Converter('mysql', 'sqlite'))->apply($dump, $target);

        $this->assertSame(3, $executed);

        $this->assertSame(
            ['a', 'b'],
            (new Model($target))->table('t')->order('id')->pluck('v')
        );
    }

    public function testApplyRefusesAMismatchedConnection(): void
    {
        Connection::add(['driver' => 'mysql', 'host' => 'db', 'database' => 'x'], 'wrong');

        $this->expectException(ConverterException::class);
        $this->expectExceptionMessageMatches('/targets \[pgsql\]/');

        (new Converter('mysql', 'pgsql'))->apply('CREATE TABLE t (a int);', 'wrong');
    }

    // -----------------------------------------------------------------------
    // Type lexicon
    // -----------------------------------------------------------------------

    /** @dataProvider nativeTypeProvider */
    public function testTypeLexiconReadsNativeTypes(string $dialect, string $native, ?string $expected): void
    {
        $this->assertSame($expected, (new TypeLexicon($dialect))->toCanonical($native));
    }

    /** @return array<string,array{string,string,?string}> */
    public static function nativeTypeProvider(): array
    {
        return [
            'mysql int'          => ['mysql', 'int(10) unsigned', 'integer'],
            'mysql varchar'      => ['mysql', 'varchar(190)', 'string'],
            'mysql longtext'     => ['mysql', 'LONGTEXT', 'longText'],
            'mysql enum'         => ['mysql', "enum('a','b')", 'enum'],
            'mysql decimal'      => ['mysql', 'decimal(8,2)', 'decimal'],
            'pg serial'          => ['pgsql', 'serial', 'id'],
            'pg bigserial'       => ['pgsql', 'bigserial', 'bigId'],
            'pg varying'         => ['pgsql', 'character varying(190)', 'string'],
            'pg double'          => ['pgsql', 'double precision', 'double'],
            'pg timestamptz'     => ['pgsql', 'timestamp with time zone', 'timestamp'],
            'pg jsonb'           => ['pgsql', 'jsonb', 'json'],
            'pg bytea'           => ['pgsql', 'bytea', 'blob'],
            'pg bit is not bool' => ['pgsql', 'bit(8)', 'string'],
            'sqlsrv nvarchar'    => ['sqlsrv', 'nvarchar(max)', 'string'],
            'sqlsrv rowversion'  => ['sqlsrv', 'timestamp', 'binary'],
            'unknown'            => ['mysql', 'geometry', null],
        ];
    }

    /**
     * The lexicon is the inverse of the grammars' type tables. If a canonical
     * type emits SQL the lexicon cannot read back, a round-trip conversion
     * silently degrades it.
     *
     * @dataProvider roundTripProvider
     */
    public function testCanonicalTypesSurviveARoundTrip(string $canonical, string $columnSql): void
    {
        $sql = "CREATE TABLE t ({$columnSql});";

        // mysql -> mysql must be a no-op in canonical terms.
        $out = (new Converter('mysql', 'mysql'))->convert($sql);

        $this->assertStringContainsString('`c`', $out, "Column lost for canonical type [{$canonical}]");

        $again = (new Converter('mysql', 'mysql'))->convert($out);

        $this->assertSame($out, $again, "Type [{$canonical}] is not stable across a round trip");
    }

    // -----------------------------------------------------------------------
    // Driver-to-driver migration
    // -----------------------------------------------------------------------

    /**
     * Build a populated SQLite database on disk and return its connection name.
     *
     * A file rather than :memory: because dump() introspects the same handle —
     * and the data deliberately includes a newline, an apostrophe and a NULL,
     * the three things that break naive quoting.
     */
    private function seedSqliteSource(string $name = 'migrate_src'): string
    {
        $this->requireSqlite();

        $file = $this->tempSqliteFile();
        Connection::add(['driver' => 'sqlite', 'database' => $file], $name);

        Schema::on($name)->create('users', function (Blueprint $table) {
            $table->id();
            $table->string('username', 50);
            $table->string('email', 100)->nullable();
            $table->integer('views')->default(0);
        });

        (new Model($name))->table('users')->insert([
            ['username' => 'alice',       'email' => 'a@example.com', 'views' => 10],
            ['username' => "bob's crew",  'email' => null,            'views' => 0],
            ['username' => "multi\nline", 'email' => 'c@x.io',        'views' => 999],
        ]);

        return $name;
    }

    private function tempSqliteFile(): string
    {
        $file = tempnam(sys_get_temp_dir(), 'laika-test-');
        $this->tempFiles[] = $file;

        return $file;
    }

    /** @var string[] Files to remove in tearDown. */
    private array $tempFiles = [];

    public function testBetweenDerivesDialectsFromTheConnections(): void
    {
        $this->requireSqlite();
        Connection::add(['driver' => 'sqlite', 'database' => ':memory:'], 'a');
        Connection::add(['driver' => 'sqlite', 'database' => ':memory:'], 'b');

        $converter = Converter::between('a', 'b');

        $this->assertSame('sqlite', $converter->sourceDialect());
        $this->assertSame('sqlite', $converter->targetDialect());
    }

    public function testMigrateCopiesEveryRowAcrossConnections(): void
    {
        $source = $this->seedSqliteSource();
        $target = $this->sqliteTarget('migrate_dst');

        $executed = Converter::between($source, $target)->migrate();

        $this->assertGreaterThan(0, $executed);

        $before = (new Model($source))->table('users')->order('id')->get();
        $after  = (new Model($target))->table('users')->order('id')->get();

        // Not just the count: the apostrophe, the embedded newline and the NULL
        // all have to survive the round trip through generated SQL.
        $this->assertSame($before, $after);
    }

    public function testMigrateRejectsASourceConnectionOfTheWrongDriver(): void
    {
        $source = $this->seedSqliteSource();
        $target = $this->sqliteTarget('migrate_dst');

        // apply() guards the target; this proves the source is guarded too.
        $this->expectException(ConverterException::class);
        $this->expectExceptionMessage('but this converter reads [mysql]');

        (new Converter('mysql', 'sqlite'))->migrate($source, $target);
    }

    public function testMigrateNeedsBothConnectionNames(): void
    {
        $this->expectException(ConverterException::class);
        $this->expectExceptionMessage('needs both connection names');

        (new Converter('sqlite', 'sqlite'))->migrate();
    }

    public function testMigrateRemovesItsTemporaryDump(): void
    {
        $source = $this->seedSqliteSource();
        $target = $this->sqliteTarget('migrate_dst');

        $before = count(glob(sys_get_temp_dir() . '/laika-migrate-*'));
        Converter::between($source, $target)->migrate();
        $after = count(glob(sys_get_temp_dir() . '/laika-migrate-*'));

        $this->assertSame($before, $after, 'migrate() leaked its intermediate dump file');
    }

    public function testMigrateRemovesItsTemporaryDumpEvenWhenApplyFails(): void
    {
        $source = $this->seedSqliteSource();

        // A target whose driver disagrees makes apply() throw after the dump
        // has already been written — the case a naive unlink() would miss.
        Connection::add(['driver' => 'sqlite', 'database' => ':memory:'], 'migrate_dst');

        $before = count(glob(sys_get_temp_dir() . '/laika-migrate-*'));

        try {
            (new Converter('sqlite', 'mysql'))->migrate($source, 'migrate_dst');
            $this->fail('Expected the driver mismatch to throw.');
        } catch (ConverterException $e) {
            // expected
        }

        $this->assertSame(
            $before,
            count(glob(sys_get_temp_dir() . '/laika-migrate-*')),
            'A failed migrate() left its dump behind'
        );
    }

    public function testMigrateKeepsTheDumpWhenAskedTo(): void
    {
        $source = $this->seedSqliteSource();
        $target = $this->sqliteTarget('migrate_dst');

        $keep = $this->tempSqliteFile();
        Converter::between($source, $target)->migrate(keep: $keep);

        $this->assertFileExists($keep);
        $this->assertStringContainsString('CREATE TABLE', (string) file_get_contents($keep));
    }

    public function testDumpRefusesDriversTheConverterCannotRead(): void
    {
        // firebird and oci have Backup support but no grammar and no lexicon,
        // so a dump of them could never be converted.
        Connection::add([
            'driver'   => 'firebird',
            'database' => 'C:\\nonexistent.fdb',
            'username' => 'sysdba',
            'password' => 'x',
        ], 'fb');

        try {
            $backup = new Backup('fb');
        } catch (\Throwable $e) {
            $this->markTestSkipped('pdo_firebird is not loaded.');
        }

        $this->expectException(BackupException::class);
        $this->expectExceptionMessage('SQL Dump Not Supported');

        $backup->dump($this->tempSqliteFile());
    }

    // -----------------------------------------------------------------------
    // PostgreSQL dump artefacts
    // -----------------------------------------------------------------------

    /**
     * pg_dump 18 wraps its output in \restrict / \unrestrict. Those are psql
     * client commands, not SQL, and they end at the newline rather than the
     * delimiter — so the splitter hands them over glued to the next statement.
     *
     * @dataProvider psqlMetaCommandProvider
     */
    public function testPsqlMetaCommandsAreNotTreatedAsSql(string $sql): void
    {
        $converter = new Converter('pgsql', 'mysql');

        $this->assertSame('', $converter->convert($sql));
    }

    /** @return array<string,array{string}> */
    public static function psqlMetaCommandProvider(): array
    {
        return [
            // The exact shape that crashed: the meta-command arrives fused to
            // the SET that follows it, because neither ends the statement.
            'restrict with the SET it is fused to' => [
                "--\n-- PostgreSQL database dump\n--\n"
                . "\\restrict RIXMc7DLS4eclgx1rSJy1BhpLMoLgvgIkqgIgtVPkX\n"
                . "-- Dumped from database version 18.1\n"
                . 'SET statement_timeout = 0;',
            ],
            'trailing unrestrict' => ["\\unrestrict RIXMc7DLS4eclgx1rSJy1BhpLMoLgvgIkqgIgtVPkX\n"],
            'connect'             => ["\\connect mydb\n"],
        ];
    }

    /**
     * The meta-command is stripped, not the statement behind it — the failure
     * mode of fixing this by discarding through to the next delimiter.
     */
    public function testSqlFollowingAMetaCommandStillConverts(): void
    {
        $converter = new Converter('pgsql', 'mysql');

        $out = $converter->convert(
            "\\restrict TOKEN123\nCREATE TABLE public.users (id integer NOT NULL);"
        );

        $this->assertStringContainsString('CREATE TABLE `users`', $out);
    }

    /**
     * pg_dump does not put the key inside CREATE TABLE the way mysqldump does;
     * it reattaches it afterwards. Dropping these would yield a keyless table.
     *
     * @dataProvider alterTableProvider
     */
    public function testAlterTableConstraintsAreTranslated(string $sql, string $expected): void
    {
        $converter = new Converter('pgsql', 'mysql');

        $this->assertSame($expected, trim($converter->convert($sql)));
        $this->assertSame([], $converter->report()->warnings());
    }

    /** @return array<string,array{string,string}> */
    public static function alterTableProvider(): array
    {
        return [
            'primary key' => [
                "ALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_pkey PRIMARY KEY (id);",
                'ALTER TABLE `users` ADD PRIMARY KEY (`id`);',
            ],
            'composite primary key' => [
                'ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (a, b);',
                'ALTER TABLE `t` ADD PRIMARY KEY (`a`, `b`);',
            ],
            // Emitted as a unique index: it means the same thing and is the one
            // spelling every target accepts, SQLite included.
            'unique' => [
                'ALTER TABLE ONLY public.users ADD CONSTRAINT uq_users_username UNIQUE (username);',
                'CREATE UNIQUE INDEX `uq_users_username` ON `users` (`username`);',
            ],
            'foreign key with actions' => [
                'ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_user_fk '
                    . 'FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;',
                'ALTER TABLE `posts` ADD CONSTRAINT `posts_user_fk` FOREIGN KEY (`user_id`) '
                    . 'REFERENCES `users` (`id`) ON DELETE CASCADE;',
            ],
        ];
    }

    /** @dataProvider droppedPostgresStatementProvider */
    public function testPostgresPlumbingIsDroppedNotPassedThrough(string $sql): void
    {
        $converter = new Converter('pgsql', 'mysql');

        $this->assertSame('', $converter->convert($sql));
        $this->assertSame(
            Warning::LEVEL_SKIPPED,
            $converter->report()->warnings()[0]->level
        );
    }

    /** @return array<string,array{string}> */
    public static function droppedPostgresStatementProvider(): array
    {
        return [
            'create sequence' => ['CREATE SEQUENCE public.users_id_seq AS integer START WITH 1;'],
            'alter sequence'  => ['ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;'],
            'setval'          => ["SELECT pg_catalog.setval('public.users_id_seq', 1, false);"],
            'set_config'      => ["SELECT pg_catalog.set_config('search_path', '', false);"],
            'owner to'        => ['ALTER TABLE public.users OWNER TO postgres;'],
        ];
    }

    /**
     * MySQL rejects AUTO_INCREMENT on a column that is not yet a key, and
     * pg_dump sets the sequence default *before* it adds the primary key. The
     * converter has to reorder them or the migration fails.
     */
    public function testAutoIncrementIsEmittedAfterThePrimaryKey(): void
    {
        $dump = <<<'SQL'
        CREATE TABLE public.users (
            id integer NOT NULL,
            username character varying(50) NOT NULL
        );
        ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
        ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
        SQL;

        $out = iterator_to_array((new Converter('pgsql', 'mysql'))->stream($dump), false);

        $primaryKey    = $this->indexOfStatement($out, 'ADD PRIMARY KEY');
        $autoIncrement = $this->indexOfStatement($out, 'AUTO_INCREMENT');

        $this->assertNotNull($primaryKey, 'The primary key was lost.');
        $this->assertNotNull($autoIncrement, 'The auto-increment was lost.');
        $this->assertGreaterThan(
            $primaryKey,
            $autoIncrement,
            'AUTO_INCREMENT must follow the PRIMARY KEY or MySQL rejects it'
        );
    }

    /** @param string[] $statements */
    private function indexOfStatement(array $statements, string $needle): ?int
    {
        foreach ($statements as $i => $sql) {
            if (str_contains($sql, $needle)) {
                return $i;
            }
        }

        return null;
    }

    /**
     * SQLite cannot attach a constraint to an existing table at all, so these
     * have to be reported rather than emitted as SQL that would fail.
     *
     * @dataProvider sqliteUnsupportedAlterProvider
     */
    public function testConstraintsSqliteCannotAddAreReported(string $sql): void
    {
        $converter = new Converter('pgsql', 'sqlite');

        $this->assertSame('', $converter->convert($sql));
        $this->assertSame(
            Warning::LEVEL_SKIPPED,
            $converter->report()->warnings()[0]->level
        );
    }

    /** @return array<string,array{string}> */
    public static function sqliteUnsupportedAlterProvider(): array
    {
        return [
            'primary key' => ['ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);'],
            'foreign key' => [
                'ALTER TABLE ONLY public.posts ADD CONSTRAINT fk FOREIGN KEY (uid) REFERENCES public.users(id);',
            ],
            'auto increment' => [
                "ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('s'::regclass);",
            ],
        ];
    }

    /**
     * The new parser must not become a silent sink for ALTER TABLE forms it
     * does not understand.
     */
    public function testUnrecognisedAlterTableStillPassesThroughWithAWarning(): void
    {
        $converter = new Converter('pgsql', 'mysql');
        $sql       = 'ALTER TABLE public.users ADD CONSTRAINT chk CHECK (id > 0);';

        $out = trim($converter->convert($sql));

        $this->assertNotSame('', $out);
        $this->assertSame(
            Warning::LEVEL_PASSTHROUGH,
            $converter->report()->warnings()[0]->level
        );
    }

    // -----------------------------------------------------------------------
    // COPY ... FROM stdin
    // -----------------------------------------------------------------------

    /**
     * pg_dump writes table data as a COPY bulk stream unless --inserts is
     * passed. Passing that block through leaves a file that looks converted but
     * whose every row is still PostgreSQL wire format.
     */
    public function testCopyBlockBecomesInserts(): void
    {
        $sql = "COPY public.users (id, username) FROM stdin;\n"
            . "1\talice\n"
            . "2\tbob\n"
            . "\\.\n";

        $out = (new Converter('pgsql', 'mysql'))->convert($sql);

        $this->assertSame(
            "INSERT INTO `users` (`id`, `username`) VALUES ('1', 'alice');\n"
            . "INSERT INTO `users` (`id`, `username`) VALUES ('2', 'bob');",
            $out
        );
    }

    /** Without a column list the row is positional, exactly as an INSERT is. */
    public function testCopyWithoutAColumnListIsPositional(): void
    {
        $sql = "COPY public.users FROM stdin;\n1\talice\n\\.\n";

        $this->assertSame(
            "INSERT INTO `users` VALUES ('1', 'alice');",
            (new Converter('pgsql', 'mysql'))->convert($sql)
        );
    }

    /**
     * \N is NULL; an empty field is the empty string. Conflating the two would
     * quietly rewrite the data.
     */
    public function testCopyDistinguishesNullFromEmptyString(): void
    {
        $sql = "COPY public.t (a, b) FROM stdin;\n\\N\t\n\\.\n";

        $this->assertSame(
            "INSERT INTO `t` (`a`, `b`) VALUES (NULL, '');",
            (new Converter('pgsql', 'mysql'))->convert($sql)
        );
    }

    /** @dataProvider copyEscapeProvider */
    public function testCopyEscapesAreDecoded(string $field, string $expected): void
    {
        $sql = "COPY public.t (a) FROM stdin;\n{$field}\n\\.\n";

        $this->assertSame(
            "INSERT INTO `t` (`a`) VALUES ({$expected});",
            (new Converter('pgsql', 'mysql'))->convert($sql)
        );
    }

    /** @return array<string,array{string,string}> */
    public static function copyEscapeProvider(): array
    {
        return [
            // A literal tab inside a value has to arrive escaped, or it would
            // read as a field separator.
            'tab'        => ['a\\tb',   "'a\tb'"],
            'newline'    => ['a\\nb',   "'a\nb'"],
            'carriage'   => ['a\\rb',   "'a\rb'"],
            // Decodes to one backslash, then re-encodes as two: a backslash is
            // an escape character inside a MySQL string. Targeting SQLite, the
            // same input yields 'a\b'.
            'backslash'  => ['a\\\\b',  "'a\\\\b'"],
            'octal'      => ['\\101',   "'A'"],
            'hex'        => ['\\x41',   "'A'"],
            'apostrophe' => ["it's",    "'it''s'"],
        ];
    }

    /**
     * The block is cut on newlines, not on the delimiter — so a semicolon in
     * the data cannot split a row in half.
     */
    public function testCopyValueContainingASemicolonSurvives(): void
    {
        $sql = "COPY public.t (a) FROM stdin;\nnot; a; statement\n\\.\n";

        $this->assertSame(
            "INSERT INTO `t` (`a`) VALUES ('not; a; statement');",
            (new Converter('pgsql', 'mysql'))->convert($sql)
        );
    }

    /** A numeric column reads as a number, not as quoted digits. */
    public function testCopyEmitsNumericColumnsUnquoted(): void
    {
        $sql = "CREATE TABLE public.t (id integer NOT NULL, name character varying(10));\n"
            . "COPY public.t (id, name) FROM stdin;\n42\talice\n\\.\n";

        $this->assertStringContainsString(
            "VALUES (42, 'alice');",
            (new Converter('pgsql', 'mysql'))->convert($sql)
        );
    }

    /**
     * COPY spells booleans t/f. Reading only '1'/'true' turned every true into
     * a false — silently, since both are valid values.
     */
    public function testCopyBooleansAreNotSilentlyInverted(): void
    {
        $sql = "CREATE TABLE public.t (flag boolean);\n"
            . "COPY public.t (flag) FROM stdin;\nt\nf\n\\.\n";

        $out = (new Converter('pgsql', 'mysql'))->convert($sql);

        $this->assertStringContainsString('VALUES (1);', $out);
        $this->assertStringContainsString('VALUES (0);', $out);
    }

    /** The mode switch has to end, or every statement after it is eaten. */
    public function testSqlAfterACopyBlockStillConverts(): void
    {
        $sql = "COPY public.t (a) FROM stdin;\n1\n\\.\n"
            . "ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (a);";

        $out = (new Converter('pgsql', 'mysql'))->convert($sql);

        $this->assertStringContainsString('ALTER TABLE `t` ADD PRIMARY KEY (`a`);', $out);
    }

    /**
     * CSV is a different encoding. Decoding it with the text-format rules would
     * corrupt every row, so it is reported rather than guessed at.
     */
    public function testCopyInCsvFormatIsReportedNotMisdecoded(): void
    {
        $converter = new Converter('pgsql', 'mysql');
        $sql       = "COPY public.t (a, b) FROM stdin WITH (FORMAT csv);\n1,2\n\\.\n";

        $converter->convert($sql);

        $this->assertSame(
            Warning::LEVEL_PASSTHROUGH,
            $converter->report()->warnings()[0]->level
        );
    }

    /** COPY is PostgreSQL's; no other dialect should switch modes on it. */
    public function testCopyIsLeftAloneForNonPostgresSources(): void
    {
        $converter = new Converter('mysql', 'pgsql');

        $out = $converter->convert('COPY t FROM stdin;');

        $this->assertStringContainsString('COPY', $out);
    }

    // -----------------------------------------------------------------------
    // SQLite dump artefacts
    // -----------------------------------------------------------------------

    public function testPragmaIsDroppedRatherThanPassedThrough(): void
    {
        $converter = new Converter('sqlite', 'pgsql');

        // PRAGMA leads every sqlite3 .dump. Passing it through would reach the
        // target verbatim and fail there — no other engine has the statement.
        $this->assertSame('', $converter->convert('PRAGMA foreign_keys=OFF;'));
        $this->assertSame(
            Warning::LEVEL_SKIPPED,
            $converter->report()->warnings()[0]->level
        );
    }

    /** @dataProvider sqliteSequenceProvider */
    public function testSqliteInternalSequenceTableIsDropped(string $sql): void
    {
        $converter = new Converter('sqlite', 'pgsql');

        // sqlite_sequence is SQLite's own AUTOINCREMENT bookkeeping. It exists
        // on no other engine, so emitting it guarantees a failure.
        $this->assertSame('', $converter->convert($sql));
        $this->assertSame(
            Warning::LEVEL_SKIPPED,
            $converter->report()->warnings()[0]->level
        );
    }

    /** @return array<string,array{string}> */
    public static function sqliteSequenceProvider(): array
    {
        return [
            'insert' => ["INSERT INTO sqlite_sequence VALUES('users',3);"],
            'delete' => ['DELETE FROM sqlite_sequence;'],
            'quoted' => ['INSERT INTO "sqlite_sequence" VALUES(\'users\',3);'],
        ];
    }

    /** @return array<string,array{string,string}> */
    public static function roundTripProvider(): array
    {
        return [
            'integer'    => ['integer', '`c` INT NOT NULL'],
            'bigInteger' => ['bigInteger', '`c` BIGINT NOT NULL'],
            'string'     => ['string', '`c` VARCHAR(190) NOT NULL'],
            'char'       => ['char', '`c` CHAR(36) NOT NULL'],
            'text'       => ['text', '`c` TEXT NULL'],
            'longText'   => ['longText', '`c` LONGTEXT NULL'],
            'decimal'    => ['decimal', '`c` DECIMAL(8,2) NOT NULL'],
            'boolean'    => ['boolean', '`c` TINYINT(1) NOT NULL'],
            'date'       => ['date', '`c` DATE NULL'],
            'dateTime'   => ['dateTime', '`c` DATETIME NULL'],
            'json'       => ['json', '`c` JSON NULL'],
            'blob'       => ['blob', '`c` BLOB NULL'],
            'enum'       => ['enum', "`c` ENUM('a', 'b') NOT NULL"],
        ];
    }
}

/**
 * A driver with no Schema grammar behind it.
 *
 * Every built-in driver has one now, so this is the only way to reach the
 * converter's "no grammar for target" guard.
 */
final class GrammarlessDriver extends AbstractDriver implements DriverInterface
{
    public function getName(): string
    {
        return 'grammarless';
    }

    public function buildDsn(array $config): string
    {
        return 'sqlite::memory:';
    }
}
